package com.dbcommon.mybatis.springbootproject01.entity.autogenerato;

import java.util.Date;

public class Account extends AccountKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.resource_id
     *
     * @mbg.generated
     */
    private String resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_name
     *
     * @mbg.generated
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_read
     *
     * @mbg.generated
     */
    private String accountRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.mailaddress
     *
     * @mbg.generated
     */
    private String mailaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_login_datetime
     *
     * @mbg.generated
     */
    private Date lastLoginDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.active
     *
     * @mbg.generated
     */
    private String active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.create_account
     *
     * @mbg.generated
     */
    private String createAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.create_datetime
     *
     * @mbg.generated
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.update_account
     *
     * @mbg.generated
     */
    private String updateAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.update_datetime
     *
     * @mbg.generated
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.resource_id
     *
     * @return the value of account.resource_id
     *
     * @mbg.generated
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.resource_id
     *
     * @param resourceId the value for account.resource_id
     *
     * @mbg.generated
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_name
     *
     * @return the value of account.account_name
     *
     * @mbg.generated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_name
     *
     * @param accountName the value for account.account_name
     *
     * @mbg.generated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_read
     *
     * @return the value of account.account_read
     *
     * @mbg.generated
     */
    public String getAccountRead() {
        return accountRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_read
     *
     * @param accountRead the value for account.account_read
     *
     * @mbg.generated
     */
    public void setAccountRead(String accountRead) {
        this.accountRead = accountRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.mailaddress
     *
     * @return the value of account.mailaddress
     *
     * @mbg.generated
     */
    public String getMailaddress() {
        return mailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.mailaddress
     *
     * @param mailaddress the value for account.mailaddress
     *
     * @mbg.generated
     */
    public void setMailaddress(String mailaddress) {
        this.mailaddress = mailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.last_login_datetime
     *
     * @return the value of account.last_login_datetime
     *
     * @mbg.generated
     */
    public Date getLastLoginDatetime() {
        return lastLoginDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.last_login_datetime
     *
     * @param lastLoginDatetime the value for account.last_login_datetime
     *
     * @mbg.generated
     */
    public void setLastLoginDatetime(Date lastLoginDatetime) {
        this.lastLoginDatetime = lastLoginDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.active
     *
     * @return the value of account.active
     *
     * @mbg.generated
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.active
     *
     * @param active the value for account.active
     *
     * @mbg.generated
     */
    public void setActive(String active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.create_account
     *
     * @return the value of account.create_account
     *
     * @mbg.generated
     */
    public String getCreateAccount() {
        return createAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.create_account
     *
     * @param createAccount the value for account.create_account
     *
     * @mbg.generated
     */
    public void setCreateAccount(String createAccount) {
        this.createAccount = createAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.create_datetime
     *
     * @return the value of account.create_datetime
     *
     * @mbg.generated
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.create_datetime
     *
     * @param createDatetime the value for account.create_datetime
     *
     * @mbg.generated
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.update_account
     *
     * @return the value of account.update_account
     *
     * @mbg.generated
     */
    public String getUpdateAccount() {
        return updateAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.update_account
     *
     * @param updateAccount the value for account.update_account
     *
     * @mbg.generated
     */
    public void setUpdateAccount(String updateAccount) {
        this.updateAccount = updateAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.update_datetime
     *
     * @return the value of account.update_datetime
     *
     * @mbg.generated
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.update_datetime
     *
     * @param updateDatetime the value for account.update_datetime
     *
     * @mbg.generated
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Account other = (Account) that;
        return (this.getAccountId() == null ? other.getAccountId() == null : this.getAccountId().equals(other.getAccountId()))
            && (this.getResourceId() == null ? other.getResourceId() == null : this.getResourceId().equals(other.getResourceId()))
            && (this.getAccountName() == null ? other.getAccountName() == null : this.getAccountName().equals(other.getAccountName()))
            && (this.getAccountRead() == null ? other.getAccountRead() == null : this.getAccountRead().equals(other.getAccountRead()))
            && (this.getMailaddress() == null ? other.getMailaddress() == null : this.getMailaddress().equals(other.getMailaddress()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getLastLoginDatetime() == null ? other.getLastLoginDatetime() == null : this.getLastLoginDatetime().equals(other.getLastLoginDatetime()))
            && (this.getActive() == null ? other.getActive() == null : this.getActive().equals(other.getActive()))
            && (this.getCreateAccount() == null ? other.getCreateAccount() == null : this.getCreateAccount().equals(other.getCreateAccount()))
            && (this.getCreateDatetime() == null ? other.getCreateDatetime() == null : this.getCreateDatetime().equals(other.getCreateDatetime()))
            && (this.getUpdateAccount() == null ? other.getUpdateAccount() == null : this.getUpdateAccount().equals(other.getUpdateAccount()))
            && (this.getUpdateDatetime() == null ? other.getUpdateDatetime() == null : this.getUpdateDatetime().equals(other.getUpdateDatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAccountId() == null) ? 0 : getAccountId().hashCode());
        result = prime * result + ((getResourceId() == null) ? 0 : getResourceId().hashCode());
        result = prime * result + ((getAccountName() == null) ? 0 : getAccountName().hashCode());
        result = prime * result + ((getAccountRead() == null) ? 0 : getAccountRead().hashCode());
        result = prime * result + ((getMailaddress() == null) ? 0 : getMailaddress().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getLastLoginDatetime() == null) ? 0 : getLastLoginDatetime().hashCode());
        result = prime * result + ((getActive() == null) ? 0 : getActive().hashCode());
        result = prime * result + ((getCreateAccount() == null) ? 0 : getCreateAccount().hashCode());
        result = prime * result + ((getCreateDatetime() == null) ? 0 : getCreateDatetime().hashCode());
        result = prime * result + ((getUpdateAccount() == null) ? 0 : getUpdateAccount().hashCode());
        result = prime * result + ((getUpdateDatetime() == null) ? 0 : getUpdateDatetime().hashCode());
        return result;
    }
}